SELECT u.USERS_NAME , q.QST_ID, q.QST_TITLE, 
   q.QST_CONTENT, q.QST_REGDATE, r.RPY_ID , 
   r.RPY_REF , r.RPY_CONTENT , r.RPY_STATUS 
   FROM QUESTBOARD q ,USERSINFO u, REPLYBOARD r 
   WHERE q.QST_ID = u.USERS_ID 
   AND q.QST_SEQ = r.RPY_REF
   AND (q.QST_STATUS = 'Y' OR r.RPY_STATUS = 'Y')
   AND q.QST_SEQ = 'Q2'
    ORDER BY r.RPY_SEQ DESC;

   
UPDATE USERSINFO SET USERS_STATUS='S' WHERE USERS_ID IN (gana@naver.com, nada@naver.com);

UPDATE USERSINFO SET USERS_STATUS='S' WHERE USERS_ID IN ('gana@naver.com', 'nada@naver.com');

SELECT *
	FROM USERSINFO u ;
	
SELECT COUNT(*) 
	FROM USERSINFO u
	WHERE USERS_ID = 'elsa@disney.com';
	

--추가정보 입력

UPDATE USERSINFO
SET USERS_ADDR='서울특별시 중구 마장로5길 10', USERS_SUBTEL='01122223333'
WHERE USERS_ID='gggg'

SELECT *
	FROM USERSINFO u 
	WHERE USERS_ID = 'gggg';

SELECT NVL(MAX(PET_SEQ),0)+1 FROM PETSINFO;

INSERT INTO PETSINFO
(PET_SEQ,
	PET_OWNER, PET_NAME, PET_BDAY, PET_SPECIES, PET_GENDER, PET_NEUT, PET_REPORT)
VALUES((SELECT NVL(MAX(PET_SEQ),0)+1 FROM PETSINFO),
	'gggg', '쪼푸', '20220731', 'D', 'M', 'N', '귀여운 우리집 쪼푸');

SELECT *
	FROM PETSINFO;

SELECT USERS_ID 
	FROM USERSINFO u
	WHERE USERS_PW = 'elsa1234';
	

-- 아이디 찾기
SELECT NVL(USERS_ID, 0) AS USERS_ID 
	FROM USERSINFO u
	WHERE USERS_NAME = '김당망' AND USERS_TEL = '0101234123';
	


-- 진료 과목 찾기

SELECT HOSP_ID, a2.ANM_SPECIES 
	FROM  ANIMALCONNECT a , ANIMALCODE a2 
	WHERE a.ANM_CODE = a2.ANM_CODE 
	AND HOSP_ID = 'gana@naver.com';

-- 병원 관계자 진료문의 조회
SELECT q.QST_SEQ, q.QST_ID, u.USERS_NAME, 
		q.QST_TITLE, q.QST_CONTENT, q.QST_SPECIES,
		a1.ANM_SPECIES, q.QST_PART, a2.PART_NAME, 
		q.QST_REGDATE, q.QST_FAST
	FROM QUESTBOARD q JOIN USERSINFO u  
	ON q.QST_ID = u.USERS_ID 
	JOIN ANIMALCODE a1
	ON q.QST_SPECIES = a1.ANM_CODE
	JOIN ANIMALPART a2
	ON q.QST_PART = a2.PART_CODE
	WHERE q.QST_STATUS != 'N' AND a1.ANM_CODE = 'A'
    ORDER BY q.QST_FAST DESC, q.QST_REGDATE DESC;
   
-- 일반사용자 진료문의 조회
SELECT q.QST_SEQ, q.QST_ID, u.USERS_NAME, 
		q.QST_TITLE, q.QST_CONTENT, q.QST_SPECIES,
		a1.ANM_SPECIES, q.QST_PART, a2.PART_NAME, 
		q.QST_REGDATE, q.QST_FAST
	FROM QUESTBOARD q JOIN USERSINFO u  
	ON q.QST_ID = u.USERS_ID 
	JOIN ANIMALCODE a1
	ON q.QST_SPECIES = a1.ANM_CODE
	JOIN ANIMALPART a2
	ON q.QST_PART = a2.PART_CODE
	WHERE q.QST_STATUS != 'N'
    ORDER BY q.QST_FAST DESC, q.QST_REGDATE DESC;
   
   
   
-- 병원 상세정보 조회
   
SELECT *
	FROM USERSINFO u, 


	
	
SELECT USERS_ID, USERS_NAME, USERS_TEL,
	   USERS_STATUS, USERS_JOINDATE,  USERS_SUBTEL,
	   USERS_ADDR, USERS_CRN,
	   HOSP_OFF, HOSP_TIME, HOSP_PARK,
	   HOSP_ETC, ANM_SPECIES
	FROM USERSINFO u JOIN HOSPITAL h
	ON USERS_ID = HOSP_ID
	LEFT JOIN ANIMALCONNECT a
	ON U.USERS_ID = A.HOSP_ID
	LEFT JOIN ANIMALCODE a2
	ON a.ANM_CODE = a2.ANM_CODE
	WHERE USERS_ID = 'gana@naver.com';


SELECT HOSP_NAME, a.ANM_CODE, a2.ANM_SPECIES 
	FROM HOSPITAL h JOIN ANIMALCONNECT a
	ON h.HOSP_ID = a.HOSP_ID
	LEFT JOIN ANIMALCODE a2
	ON a.ANM_CODE = a2.ANM_CODE 
	WHERE h.HOSP_ID = 'juchu@naver.com'
	ORDER BY a2.ANM_CODE;




-- 진료동물 코드 넣기
INSERT INTO ANIMALCONNECT (ANM_CODE, HOSP_ID)
	VALUES('A', 'juchu@naver.com');

-- 진료 과목 넣기
INSERT INTO MEDICONNECT (MEDI_CODE, HOSP_ID)
	VALUES('02', 'juchu@naver.com');

SELECT *
	FROM HOSPITAL h LEFT JOIN ANIMALCONNECT a 
	ON H.HOSP_ID = A.HOSP_ID
	WHERE H.HOSP_ID = 'juchu@naver.com';

-- 진료동물 코드 수정
UPDATE ANIMALCONNECT
	SET ANM_CODE='C'
	WHERE ANM_CODE = 'A' AND HOSP_ID='juchu@naver.com';

DELETE FROM ANIMALCONNECT
	WHERE ANM_CODE='C' AND HOSP_ID='juchu@naver.com';

-- 진료과목 코드 수정
UPDATE MEDICONNECT
	SET MEDI_CODE='01'
	WHERE MEDI_CODE ='00' AND HOSP_ID='gana@naver.com';

DELETE FROM MEDICONNECT
	WHERE MEDI_CODE='01' AND HOSP_ID='gana@naver.com';



SELECT HOSP_NAME, A.ANM_CODE, A2.ANM_SPECIES, M.MEDI_CODE , M2.MEDI_NAME 
	FROM HOSPITAL h JOIN ANIMALCONNECT a
	ON H.HOSP_ID = A.HOSP_ID 
	LEFT JOIN MEDICONNECT m
	ON H.HOSP_ID = M.HOSP_ID
	LEFT JOIN ANIMALCODE a2 
	ON A.ANM_CODE = A2.ANM_CODE
	LEFT JOIN MEDICODE m2 
	ON M.MEDI_CODE = M2.MEDI_CODE
	WHERE H.HOSP_ID = 'gana@naver.com';
	
SELECT USERS_ID, USERS_NAME, USERS_TEL,
	   USERS_STATUS, TO_CHAR(USERS_JOINDATE, 'YYYY-MM-DD') AS USERS_JOINDATE,  USERS_SUBTEL,
	   USERS_ADDR, USERS_AUTH, USERS_CRN,
	   HOSP_OFF, HOSP_TIME, HOSP_PARK,
	   HOSP_ETC, ANM_SPECIES , MEDI_NAME 
	FROM USERSINFO u JOIN HOSPITAL h
	ON USERS_ID = HOSP_ID
	LEFT JOIN ANIMALCONNECT a
	ON U.USERS_ID = A.HOSP_ID
	LEFT JOIN ANIMALCODE a2
	ON a.ANM_CODE = a2.ANM_CODE
	LEFT JOIN MEDICONNECT m 
	ON u.USERS_ID = m.HOSP_ID
	LEFT JOIN MEDICODE m2 
	ON m.MEDI_CODE = m2.MEDI_CODE 
	WHERE USERS_ID =  'gana@naver.com';
	

-- 비밀번호 변경
UPDATE USERSINFO SET USERS_PW='123456789' WHERE USERS_ID='panananan@naver.com';

SELECT USERS_ID, USERS_PW 
	FROM USERSINFO u 
