----------------------------------- 진료예약 --------------------------------------------
------------------------------------- 조회 --------------------------------------------
-- 월별 - 예약확정(Y) + 예약취소(N) 건수 조회

SELECT  MM, NVL(Y_COUNT, 0) AS Y_COUNT
	FROM(
		SELECT "MONTH", COUNT(*) AS Y_COUNT
			FROM (
				SELECT TO_CHAR(RESRV_VISIT, 'MM') AS "MONTH" , RESRV_HOPS ,  RESRV_STATUS 
					FROM RESERVATION r 
					WHERE TO_CHAR(RESRV_VISIT, 'YYYY') = '2023'
						AND RESRV_STATUS ='Y'
						AND RESRV_HOPS = 'gana@naver.com'
			)
			GROUP BY "MONTH"
		) M1
	RIGHT JOIN 
		(SELECT LPAD(LEVEL,2,0) MM
			FROM DUAL
			CONNECT BY LEVEL <=12) M2
	ON M1."MONTH" = M2.MM
	ORDER BY MM;

-- 해당 아이디의 등록된 예약자 명단 
SELECT RESRV_VISIT , RESRV_NUM, RESRV_NAME  
	FROM (SELECT TO_CHAR(RESRV_VISIT,'YYYY-MM-DD')||'T'||RESRV_TIME||':00:00' AS RESRV_VISIT, RESRV_NUM, RESRV_NAME, RESRV_STATUS, RESRV_HOPS  
			FROM RESERVATION r) 
	WHERE RESRV_HOPS = 'nada@naver.com'
		AND RESRV_STATUS = 'Y'

-- 예약 상세정보를 조회할 수 있다.
SELECT RESRV_NUM, RESRV_NAME, RESRV_TEL, TO_CHAR(RESRV_VISIT,'YYYY-MM-DD') AS RESRV_VISIT, RESRV_TIME, RESRV_MEMO 
	FROM RESERVATION r 
		WHERE RESRV_NUM = 'RSV8';
	
-- 일별 예약상태에 따라 조회할 수 있다.
--
SELECT RESRV_NUM,TO_CHAR(RESRV_VISIT,'YYYY-MM-DD') AS RESRV_VISIT, RESRV_TIME, RESRV_NAME, RESRV_STATUS, TO_CHAR(RESRV_REGDATE,'YYYY-MM-DD HH24:MI:SS') AS RESRV_REGDATE 
	FROM RESERVATION r 
	WHERE RESRV_HOPS = 'gana@naver.com'
		AND RESRV_STATUS = 'W'
		ORDER BY RESRV_VISIT ;

--예약 신청페이지에 뿌려줄 병원의 정보 및 영업 시간 (오늘날짜부터 리스트 출력)
SELECT HOSP_TIME, HOSP_OFF, r.RESRV_NUM , 
		TO_CHAR(r.RESRV_VISIT,'YYYY-MM-DD')||'T'||r.RESRV_TIME||':00:00' AS RESRV_VISIT,
		r.RESRV_TIME , r.RESRV_STATUS 
	FROM HOSPITAL h LEFT JOIN RESERVATION r
	ON h.HOSP_ID = r.RESRV_HOPS 
	WHERE HOSP_ID = 'gana@naver.com'
		AND r.RESRV_STATUS IN ('Y','W')
		AND  r.RESRV_VISIT > (SELECT TO_CHAR(SYSDATE -1,'YYYY-MM-DD')  
							FROM DUAL)
	ORDER BY r.RESRV_VISIT ASC;

-- 예약정보가 아예 없는 병원 호출
SELECT HOSP_TIME, HOSP_OFF
	FROM HOSPITAL h 
	WHERE HOSP_ID = 'suwu@naver.com';

SELECT TO_CHAR(RESRV_VISIT,'YYYY-MM-DD')||'T'||r.RESRV_TIME||':00:00' AS RESRV_VISIT, RESRV_NUM 
	FROM RESERVATION r
	WHERE RESRV_VISIT > (SELECT TO_CHAR(SYSDATE -1,'YYYY-MM-DD')  
							FROM DUAL)
		AND (RESRV_STATUS = 'Y' OR RESRV_STATUS = 'W')
		AND RESRV_HOPS = 'suwu@naver.com'
	ORDER BY RESRV_VISIT ASC;
	
SELECT TO_CHAR(SYSDATE -1,'YYYY-MM-DD')  
	FROM DUAL;
	
-- (사용자) 전체 예약내역 조회
SELECT RESRV_NUM , RESRV_HOPS , RESRV_VISIT , 
		RESRV_TIME , RESRV_NAME , RESRV_MEMO ,
		RESRV_STATUS, HOSP_NAME 
	FROM (SELECT RESRV_NUM , RESRV_HOPS , TO_CHAR(RESRV_VISIT,'YYYY-MM-DD') AS RESRV_VISIT, 
				RESRV_TIME , RESRV_NAME , RESRV_MEMO , 
				RESRV_STATUS , HOSP_NAME ,ROW_NUMBER () OVER(ORDER BY r.RESRV_REGDATE DESC) RN
			FROM HOSPITAL h JOIN RESERVATION r
			ON h.HOSP_ID = r.RESRV_HOPS 
			WHERE RESRV_USERID = 'elsa@disney.com')
	WHERE RN BETWEEN '1' AND '5';

SELECT COUNT(*) 
	FROM RESERVATION r 
	WHERE RESRV_USERID = 'elsa@disney.com';

SELECT HOSP_NAME 
	FROM HOSPITAL h 
	WHERE HOSP_ID = 'gana@naver.com';


	
------------------------------------- 등록 --------------------------------------------
-- 진료예약 등록 (예약번호, 예약대기, 예약자 이름, 전화번호 , 예약시간, 메모, 병원ID)
-- - default값: 예약대기(W)상태
INSERT INTO RESERVATION (RESRV_NUM, 
						RESRV_HOPS, RESRV_VISIT, RESRV_TIME, 
						RESRV_NAME, RESRV_TEL, RESRV_MEMO, 
						RESRV_STATUS, RESRV_REGDATE) 
	VALUES((SELECT CONCAT('RSV',NVL(MAX(TO_NUMBER(SUBSTR(RESRV_NUM, 4))),0)+1) AS RESRV_NUM FROM RESERVATION r), 
			'nada@naver.com', '2023-09-10', '14', 
			'최메리다', '01098765430', '메모 입력 테스트', 
			'W',(SYSDATE));		

SELECT CONCAT('RSV',NVL(MAX(TO_NUMBER(SUBSTR(RESRV_NUM, 4))),0)+1) AS RESRV_NUM 
	FROM RESERVATION r ;
	
------------------------------------- 수정 --------------------------------------------
-- 병원관계자의 승인 시 예약대기(W)에서 예약확정(Y) 상태로 변경
UPDATE RESERVATION 
	SET RESRV_STATUS = 'Y'  
		WHERE RESRV_NUM='RSV1';
	
	
-- 환불처리가 된 예약은 예약확정(Y) 상태에서 예약취소(N) 상태로 변경
UPDATE RESERVATION 
	SET RESRV_STATUS = 'N'  
		WHERE RESRV_NUM='RSV1';

-- 예약정보 수정
UPDATE PROJECT.RESERVATION
	SET RESRV_VISIT='', RESRV_TIME='', RESRV_NAME='', RESRV_TEL='', RESRV_MEMO='',
	WHERE RESRV_NUM='';


------------------------------------- 삭제 --------------------------------------------		
-- 예약을 거절/취소한 경우 예약목록에서 삭제
	DELETE FROM RESERVATION WHERE RESRV_NUM='RSV21';


SELECT *
	FROM RESERVATION r ;

SELECT TO_CHAR(SYSDATE-2/24, 'YYYYMMDD HH24:MI:SS')
	FROM DUAL;

SELECT RESRV_NUM ,RESRV_REGDATE , RESRV_USERID 
	FROM RESERVATION r 
	WHERE RESRV_STATUS = 'W'
	AND (SYSTIMESTAMP - RESRV_REGDATE) > INTERVAL '2'HOUR;

SELECT (SYSTIMESTAMP - RESRV_REGDATE)
	FROM RESERVATION r 
	WHERE RESRV_STATUS = 'W';
---------------------------------------------------------------------------------

----------------------------------- 지도 --------------------------------------------
-- 사이트에 가입된 동물병원 불러오기
SELECT USERS_ID , USERS_NAME , USERS_TEL , USERS_ADDR
	FROM USERSINFO u
	WHERE USERS_AUTH = 'H';

-- 마커 클릭 주소 받아서 아이디 호출
SELECT USERS_ID 
	FROM USERSINFO u 
	WHERE USERS_ADDR LIKE '%광명시 철산동 634%';
	
--지도에서 마커 클릭 -> 상세조회
SELECT h.HOSP_NAME , u.USERS_TEL , u.USERS_ADDR , h.HOSP_TIME , h.HOSP_OFF , h.HOSP_ETC ,h.HOSP_PARK , h.HOSP_MNG 
	FROM USERSINFO u JOIN HOSPITAL h 
	ON u.USERS_ID = h.HOSP_ID 
	WHERE USERS_AUTH = 'H'
		AND USERS_ADDR LIKE '%광명시 철산동 634%';

-- 동물병원명을 검색하여 동물병원 목록조회 
SELECT HOSP_NAME , HOSP_MNG , USERS_TEL , USERS_ADDR
	FROM (SELECT h.HOSP_NAME , h.HOSP_MNG , u.USERS_TEL , u.USERS_ADDR, 
				ROW_NUMBER () OVER(ORDER BY HOSP_NAME) RN
			FROM HOSPITAL h JOIN USERSINFO u 
				ON h.HOSP_ID = u.USERS_ID 
			WHERE HOSP_NAME LIKE '%동물%')
	WHERE RN BETWEEN '1' AND '5';

-- 주소 선택(시/도, 시/군/구) 하여 해당 지역의 동물병원 위치 지도에 표시
SELECT h.HOSP_NAME , HOSP_PARK , u.USERS_TEL , u.USERS_ADDR 
	FROM USERSINFO u JOIN HOSPITAL h
		ON h.HOSP_ID = u.USERS_ID 
	WHERE u.USERS_ADDR LIKE '%금천구%';

-- 진료가능 동물 / 진료과목 / 운영형태 / 주차 선택하여 동물병원 위치표시
-- 운영형태
SELECT h.HOSP_NAME, u.USERS_ADDR , u.USERS_TEL  
	FROM HOSPITAL h 
	JOIN USERSINFO u ON h.HOSP_ID = u.USERS_ID 
	WHERE h.HOSP_MNG = 'E' ;

-- 주차가능
SELECT h.HOSP_NAME, u.USERS_ADDR , u.USERS_TEL  
	FROM HOSPITAL h 
	JOIN USERSINFO u ON h.HOSP_ID = u.USERS_ID 
	WHERE h.HOSP_PARK = 'Y';  

-- 운영형태 + 주차가능 (다중선택)
SELECT h.HOSP_NAME, u.USERS_ADDR , u.USERS_TEL  
	FROM HOSPITAL h 
	JOIN USERSINFO u ON h.HOSP_ID = u.USERS_ID 
	WHERE h.HOSP_MNG = 'G'
		AND h.HOSP_PARK = 'Y'; 
	
-- 진료가능 동물 (단일선택)
SELECT h.HOSP_NAME, u.USERS_ADDR , a.ANM_CODE 
	FROM HOSPITAL h 
	JOIN USERSINFO u ON h.HOSP_ID = u.USERS_ID 
	JOIN ANIMALCONNECT a ON a.HOSP_ID = h.HOSP_ID
	WHERE a.ANM_CODE = 'D';

-- 진료과목 (단일선택)
SELECT h.HOSP_NAME, u.USERS_ADDR , m.MEDI_CODE 
	FROM HOSPITAL h 
	JOIN USERSINFO u ON h.HOSP_ID = u.USERS_ID 
	JOIN MEDICONNECT m ON m.HOSP_ID = h.HOSP_ID 
	WHERE m.MEDI_CODE = '00';


SELECT *
	FROM HOSPITAL h ;
SELECT *
	FROM USERSINFO u 
	WHERE USERS_AUTH = 'H';
	

INSERT INTO RESERVATION (RESRV_NUM, RESRV_HOPS, RESRV_VISIT, RESRV_TIME, RESRV_NAME, RESRV_TEL, RESRV_MEMO, RESRV_STATUS, RESRV_REGDATE) 
	VALUES('RSV22', 'gana@naver.com', '2023-09-12', '10', '김엘사', '01012345678', '메모1', 'Y',TO_DATE('2023-09-11 15:10:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RESERVATION (RESRV_NUM, RESRV_HOPS, RESRV_VISIT, RESRV_TIME, RESRV_NAME, RESRV_TEL, RESRV_MEMO, RESRV_STATUS, RESRV_REGDATE) 
	VALUES('RSV23', 'gana@naver.com', '2023-09-12', '11', '김안나', '01056781234', '메모2', 'Y',TO_DATE('2023-09-11 15:20:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RESERVATION (RESRV_NUM, RESRV_HOPS, RESRV_VISIT, RESRV_TIME, RESRV_NAME, RESRV_TEL, RESRV_MEMO, RESRV_STATUS, RESRV_REGDATE) 
	VALUES('RSV24', 'gana@naver.com', '2023-09-12', '13', '최메리다', '01098765430', '메모3', 'Y',TO_DATE('2023-09-11 15:30:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RESERVATION (RESRV_NUM, RESRV_HOPS, RESRV_VISIT, RESRV_TIME, RESRV_NAME, RESRV_TEL, RESRV_MEMO, RESRV_STATUS, RESRV_REGDATE) 
	VALUES('RSV25', 'gana@naver.com', '2023-09-12', '14', '이자스민', '01055667788', '메모4', 'Y',TO_DATE('2023-09-11 15:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RESERVATION (RESRV_NUM, RESRV_HOPS, RESRV_VISIT, RESRV_TIME, RESRV_NAME, RESRV_TEL, RESRV_MEMO, RESRV_STATUS, RESRV_REGDATE) 
	VALUES('RSV26', 'gana@naver.com', '2023-09-12', '15', '박백설', '01099887766', '메모5', 'Y',TO_DATE('2023-09-11 15:10:00','YYYY-MM-DD HH24:MI:SS'));	

--병원상세조회 
SELECT u.USERS_ID , u.USERS_TEL , u.USERS_ADDR , u.USERS_SUBTEL , 
		h.HOSP_NAME, h.HOSP_TIME , h.HOSP_OFF , h.HOSP_PARK , 
		h.HOSP_ETC , h.HOSP_MNG  
	FROM USERSINFO u JOIN HOSPITAL h 
		ON u.USERS_ID = h.HOSP_ID 
	WHERE USERS_ID = 'gana@naver.com';
--병원 진료동물 조회
SELECT a.ANM_CODE , a2.ANM_SPECIES 
	FROM ANIMALCONNECT a JOIN ANIMALCODE a2 
		ON a.ANM_CODE = a2.ANM_CODE
	WHERE a.HOSP_ID = 'gana@naver.com'
	ORDER BY a.ANM_CODE ASC;
--병원 진료과목 조회
SELECT m.MEDI_CODE , m2.MEDI_NAME 
	FROM MEDICONNECT m JOIN MEDICODE m2 
		ON m.MEDI_CODE  = m2.MEDI_CODE 
	WHERE m.HOSP_ID = 'gana@naver.com'
	ORDER BY MEDI_CODE ASC;
	
SELECT RESRV_NUM,TO_CHAR(RESRV_VISIT,'YYYY-MM-DD') AS RESRV_VISIT, RESRV_TIME, 
		RESRV_NAME, RESRV_STATUS, TO_CHAR(RESRV_REGDATE,'YYYY-MM-DD HH24:MI:SS') AS RESRV_REGDATE ,
		RESRV_USERID 
			FROM RESERVATION r 
			WHERE RESRV_HOPS = 'gana@naver.com'
				AND RESRV_STATUS = 'Y'
				ORDER BY RESRV_VISIT ;
				

-- 현재시간과 예약시간 비교
SELECT TO_DATE(TO_CHAR(SYSDATE,'yyyy-MM-dd')) - (
				SELECT TO_DATE(TO_CHAR(RESRV_VISIT,'yyyy-MM-dd')) AS RESRV_VISIT 
					FROM RESERVATION r 
					WHERE RESRV_NUM = 'RSV37'
				) AS TIMER
	FROM DUAL;


SELECT SI_DO 
	FROM REGION_DATA rd 
	GROUP BY SI_DO;

SELECT SI_GUN_GU 
	FROM REGION_DATA rd 
	WHERE SI_DO = '경기도';

SELECT 소재지전체주소 , 사업장명
	FROM HOSPITAL_DATA hd 
	WHERE 도로명전체주소 LIKE '인천광역시%미추홀구%';

SELECT *
	FROM REPLYBOARD r 
--	WHERE RPY_CHOSEN = 'Y';

-- 답글 수 대비 채택 1~3위
SELECT 	u.USERS_NAME , RPY_ID, RPY_CNT, RPY_CHOSEN, RN 
	FROM(SELECT RPY_ID, RPY_CNT, RPY_CHOSEN, 
				ROW_NUMBER () OVER (ORDER BY RPY_CHOSEN DESC, RPY_CNT ASC) AS RN
			FROM (SELECT RPY_ID , COUNT(RPY_ID) AS RPY_CNT , COUNT(CASE WHEN RPY_CHOSEN='Y' THEN 1 END) AS RPY_CHOSEN
					FROM REPLYBOARD r 
					GROUP BY RPY_ID )) r2
	JOIN USERSINFO u ON u.USERS_ID = r2.RPY_ID 
	WHERE RN BETWEEN '1' AND '3';


-- 해당 아이디의 답글 수, 채택 수
SELECT RPY_ID , COUNT(RPY_ID) AS RPY_CNT , COUNT(CASE WHEN RPY_CHOSEN='Y' THEN 1 END) AS RPY_CHOSEN
		FROM REPLYBOARD r 
		GROUP BY RPY_ID
		HAVING RPY_ID = 'gana@naver.com';
					

