SELECT PET_SEQ , PET_NAME , PET_SPECIES , PET_GENDER
	FROM PETSINFO p 
	WHERE PET_SEQ = 1;

SELECT m.MEDI_NUM, m.MEDI_ID , m.MPET_SEQ , p.PET_NAME, m.MEDI_L , m2.MEDI_NAME , m.MEDI_S , m3.MEDI_NAME, m.MEDI_TITLE, m.MEDI_VISIT  
	FROM MEDICHART m 
	JOIN MEDICODE m2 ON m.MEDI_L = m2.MEDI_CODE 
	LEFT JOIN MEDICODE m3 ON m.MEDI_S = m3.MEDI_CODE 
	JOIN PETSINFO p ON m.MPET_SEQ = p.PET_SEQ 
	WHERE m.MEDI_ID ='merida@disney.com'
	AND m.MEDI_DELFLAG ='N'
	ORDER BY m.MEDI_VISIT DESC;

	
SELECT m.MEDI_NUM, m.MEDI_ID , m.MPET_SEQ , p.PET_NAME, m.MEDI_L , m2.MEDI_NAME , m.MEDI_S , m2.MEDI_NAME, m.MEDI_TITLE, m.MEDI_VISIT  
			FROM PETSINFO p 
			JOIN MEDICHART m  ON p.PET_SEQ = m.MPET_SEQ 
			LEFT JOIN MEDICODE m2 ON m.MEDI_S = m2.MEDI_CODE 
			WHERE p.PET_OWNER ='elsa@disney.com' 
			AND m.MEDI_DELFLAG ='N'
			AND p.PET_NAME ='후추'
			ORDER BY MEDI_VISIT DESC;
			
SELECT m.MEDI_NUM, m.MEDI_ID , m.MPET_SEQ , p.PET_NAME, m.MEDI_L ,m2.MEDI_NAME, m.MEDI_S,m3.MEDI_NAME ,m.MEDI_TITLE, m.MEDI_VISIT 
			FROM PETSINFO p 
			JOIN MEDICHART m  ON p.PET_SEQ = m.MPET_SEQ 
			LEFT JOIN MEDICODE m2 ON m.MEDI_L = m2.MEDI_CODE
			LEFT JOIN MEDICODE m3 ON m.MEDI_S = m3.MEDI_NAME 
			WHERE p.PET_OWNER ='elsa@disney.com' 
			AND m.MEDI_DELFLAG ='N'
			AND p.PET_NAME ='후추'
			ORDER BY MEDI_VISIT DESC;
			
		
SELECT MEDI_CODE , MEDI_NAME 
	FROM MEDICODE;
	

SELECT m.MEDI_NUM, m.MEDI_ID , m.MPET_SEQ , 
				p.PET_NAME, m.MEDI_L , m2.MEDI_NAME , 
				m.MEDI_S , m3.MEDI_NAME, m.MEDI_TITLE, m.MEDI_VISIT  
			FROM MEDICHART m 
			JOIN MEDICODE m2 ON m.MEDI_L = m2.MEDI_CODE 
			LEFT JOIN MEDICODE m3 ON m.MEDI_S = m3.MEDI_CODE 
			JOIN PETSINFO p ON m.MPET_SEQ = p.PET_SEQ 
			WHERE m.MEDI_ID = 'elsa@disney.com'
			AND m.MEDI_DELFLAG ='N'
			ORDER BY m.MEDI_VISIT DESC;
			
SELECT p.PET_SEQ ,p.PET_OWNER, p.PET_NAME, p.PET_BDAY ,
		p.PET_SPECIES ,p.PET_GENDER, p.PET_NEUT ,p.PET_REPORT ,
		m.MEDI_NUM ,m.MEDI_VISIT, 
		m.MEDI_L, m2.MEDI_NAME , m.MEDI_S, m3.MEDI_NAME , 
		m.MEDI_TITLE , m.MEDI_CONTENT ,m.MEDI_DELFLAG
	FROM PETSINFO p 
	JOIN MEDICHART m ON p.PET_SEQ = m.MPET_SEQ 
	LEFT JOIN MEDICODE m2 ON m.MEDI_L = m2.MEDI_CODE 
	LEFT JOIN MEDICODE m3 ON m.MEDI_S = m3.MEDI_CODE 
	WHERE p.PET_OWNER = 'elsa@disney.com'
	AND m.MEDI_DELFLAG ='N'
	AND m.MEDI_L='00'
	AND m.MEDI_S='001'
	ORDER BY m.MEDI_VISIT DESC;